// Code generated by go-bindata. DO NOT EDIT.
// sources:
// sql/get_bands.sql
// sql/get_face.sql
// sql/get_idol_previews.sql
// sql/get_idols.sql
// sql/get_train_data.sql
// sql/init_db.sql
// sql/upsert_band.sql
// sql/upsert_face.sql
// sql/upsert_idol.sql

package kpopnet

import (
	"bytes"
	"compress/gzip"
	"crypto/sha256"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes  []byte
	info   os.FileInfo
	digest [sha256.Size]byte
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _get_bandsSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x0a\x76\xf5\x71\x75\x0e\x51\xc8\x4c\xd1\x51\x48\x49\x2c\x49\x54\x70\x0b\xf2\xf7\x55\x48\x4a\xcc\x4b\x29\xe6\x02\x04\x00\x00\xff\xff\x14\x21\x0f\x5f\x1b\x00\x00\x00")

func get_bandsSqlBytes() ([]byte, error) {
	return bindataRead(
		_get_bandsSql,
		"get_bands.sql",
	)
}

func get_bandsSql() (*asset, error) {
	bytes, err := get_bandsSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "get_bands.sql", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0xce, 0xf3, 0x28, 0xfe, 0x9b, 0x8b, 0x77, 0x51, 0x29, 0x48, 0xac, 0xb1, 0xe6, 0x2e, 0x6a, 0xe4, 0xa7, 0x94, 0x74, 0xeb, 0xc4, 0x3b, 0x95, 0xf, 0x22, 0xa7, 0x3c, 0xd8, 0x26, 0xf4, 0xe8, 0xa2}}
	return a, nil
}

var _get_faceSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x0a\x76\xf5\x71\x75\x0e\x51\x28\x4a\x4d\x2e\x49\xcc\x4b\xcf\x49\xd5\x51\xc8\x4c\xc9\xcf\x89\xcf\x4c\x81\x32\x92\xf3\xf3\xd2\x32\x8b\x72\x53\x53\x14\xdc\x82\xfc\x7d\x15\xd2\x12\x93\x53\x8b\xb9\xc2\x3d\x5c\x83\x5c\x15\x32\x73\x13\xd3\x53\xe3\x33\x53\x14\x6c\x15\x54\x0c\xb9\x7c\x3c\x7d\x3d\x43\x14\x0c\xb9\x00\x01\x00\x00\xff\xff\xb3\x0f\xcf\x39\x51\x00\x00\x00")

func get_faceSqlBytes() ([]byte, error) {
	return bindataRead(
		_get_faceSql,
		"get_face.sql",
	)
}

func get_faceSql() (*asset, error) {
	bytes, err := get_faceSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "get_face.sql", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0xc0, 0xec, 0x53, 0x50, 0x9a, 0x38, 0x5a, 0x99, 0xa3, 0x92, 0x74, 0xac, 0x94, 0xe7, 0xfd, 0xd1, 0xbf, 0x5a, 0x22, 0x32, 0x7b, 0xdb, 0xdb, 0x40, 0x5, 0x6b, 0xf1, 0x4b, 0x89, 0xf7, 0x4c, 0xc1}}
	return a, nil
}

var _get_idol_previewsSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x0a\x76\xf5\x71\x75\x0e\x51\xc8\x4c\xd1\x51\xc8\xcc\x4d\x4c\x4f\x8d\xcf\x4c\x51\x70\x0b\xf2\xf7\x55\xc8\x4c\xc9\xcf\x89\x2f\x28\x4a\x2d\xcb\x4c\x2d\x2f\xe6\x02\x04\x00\x00\xff\xff\xb1\xe8\x17\xc4\x27\x00\x00\x00")

func get_idol_previewsSqlBytes() ([]byte, error) {
	return bindataRead(
		_get_idol_previewsSql,
		"get_idol_previews.sql",
	)
}

func get_idol_previewsSql() (*asset, error) {
	bytes, err := get_idol_previewsSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "get_idol_previews.sql", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0x9c, 0xa5, 0x88, 0x6e, 0xa2, 0x98, 0x90, 0xdd, 0x3b, 0xbc, 0xf2, 0x37, 0xb7, 0x68, 0xb0, 0x3d, 0x94, 0x69, 0x24, 0xe2, 0x7f, 0xb5, 0x7, 0x2a, 0x7b, 0xb5, 0x6e, 0xad, 0x1, 0xa3, 0x9b, 0xeb}}
	return a, nil
}

var _get_idolsSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x0a\x76\xf5\x71\x75\x0e\x51\xc8\x4c\xd1\x51\x48\x4a\xcc\x4b\x89\x07\x31\x52\x12\x4b\x12\x15\xdc\x82\xfc\x7d\x15\x32\x53\xf2\x73\x8a\xb9\x00\x01\x00\x00\xff\xff\xd9\x11\x11\x34\x24\x00\x00\x00")

func get_idolsSqlBytes() ([]byte, error) {
	return bindataRead(
		_get_idolsSql,
		"get_idols.sql",
	)
}

func get_idolsSql() (*asset, error) {
	bytes, err := get_idolsSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "get_idols.sql", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0x38, 0x44, 0xfe, 0xcc, 0x62, 0x3d, 0x28, 0x78, 0xf2, 0xd7, 0x53, 0xfa, 0x71, 0xf0, 0xe5, 0xcb, 0x5c, 0xa8, 0xd2, 0xf, 0x89, 0xcb, 0x9, 0xa4, 0x8f, 0xcb, 0x78, 0xdd, 0x79, 0xfd, 0x28, 0xa9}}
	return a, nil
}

var _get_train_dataSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x0a\x76\xf5\x71\x75\x0e\x51\xc8\x4c\xc9\xcf\x89\xcf\x4c\xd1\x51\x48\x49\x2d\x4e\x2e\xca\x2c\x28\xc9\x2f\x52\x70\x0b\xf2\xf7\x55\x48\x4b\x4c\x4e\x2d\xe6\x0a\xf7\x70\x0d\x72\x85\x28\x4a\xce\xcf\x4b\xcb\x2c\xca\x4d\x4d\x51\xb0\x55\x08\x09\x0a\x75\xe5\xf2\x0f\x72\x71\x0d\x52\x70\x8a\x84\x99\xc1\x05\x08\x00\x00\xff\xff\x24\x9f\xe9\xe0\x53\x00\x00\x00")

func get_train_dataSqlBytes() ([]byte, error) {
	return bindataRead(
		_get_train_dataSql,
		"get_train_data.sql",
	)
}

func get_train_dataSql() (*asset, error) {
	bytes, err := get_train_dataSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "get_train_data.sql", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0x3b, 0x1e, 0xfd, 0x55, 0x2b, 0x14, 0x88, 0xb8, 0x52, 0xc, 0xb2, 0x89, 0x24, 0xd6, 0x28, 0xef, 0x10, 0x5e, 0x2b, 0xc3, 0xc0, 0x7, 0x8c, 0x77, 0x7f, 0x42, 0xcc, 0x98, 0x7e, 0x7c, 0x27, 0xdc}}
	return a, nil
}

var _init_dbSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x9c\x93\x51\x6f\x9b\x30\x10\xc7\xdf\xf9\x14\xb7\xa7\x80\xd4\x56\xcd\xb4\xbd\xac\x9a\x26\x06\x8e\x86\xc2\x48\x47\x88\x44\x9f\xa2\xc3\xbe\x10\x4f\xc4\x8e\x8c\xd3\x75\xdf\x7e\x82\xc4\x25\xad\x52\x34\xf5\x0d\x1d\x3e\xfc\xfb\xff\xee\x88\x72\x16\x16\x0c\x8a\xf0\x7b\xca\x20\x99\x41\xb6\x28\x80\x95\xc9\xb2\x58\x42\x85\x4a\xb4\xe0\x7b\x00\x52\xc0\xe1\x20\x05\xdc\xe7\xc9\xcf\x30\x7f\x80\x39\x7b\xb8\xf2\x00\x04\x5a\x84\xdf\xad\x56\x55\xdf\x96\xad\xd2\xb4\x2b\x47\x3f\x58\x34\x07\x3f\x5b\x14\x7e\x7f\xe2\x1b\x4c\xa4\x98\x04\x10\x66\x31\xb8\x82\xc2\x1d\x4d\x02\x2f\xb8\xf3\xbc\x11\x02\x29\x74\x33\x4a\xd0\x21\xae\xdd\x3b\xc7\x00\x39\x9b\xb1\x9c\x65\x11\x73\x19\x16\x19\xc4\x2c\x65\x05\x83\x28\x5c\x46\x61\xcc\xde\x49\x7f\x5e\x3c\x5d\xfd\x76\xae\xeb\x6b\x28\xcb\xd2\x9f\x63\x8d\x3b\x19\x7c\x81\x7b\x34\x16\xf4\x06\xf8\xc1\x12\xdf\xa2\xba\x19\x4d\xbe\xc3\x9a\x8e\xd1\xdb\x2d\x4e\x81\x6f\xd1\xf8\x9f\x6e\x83\x73\x01\xff\x63\x6f\xbd\x37\xf4\x28\xe9\xcf\x9b\x16\xcf\x65\x1d\x75\x5f\x94\xd5\xf3\x74\xa6\x9f\x41\x56\x59\xf2\x6b\xc5\x2e\x4a\x3f\xc2\x3b\x09\xb1\x56\x13\x0b\x86\x36\x64\x48\x71\x72\xd1\xac\x86\x8a\x00\xab\x86\xba\xc7\xbd\xa1\x46\xa3\x00\x41\x2d\x37\x72\x6f\xb5\x69\x6f\xba\xe6\x62\x11\x2f\x06\x85\x89\x12\xf4\x44\xed\x87\xb1\xd4\x1b\xe4\xf4\x9c\xb6\x92\x75\x4b\x46\x62\xf3\x7a\x71\x0c\x71\x8b\xaa\x6e\x08\x2a\xfd\xf4\x62\xfe\x03\x01\x54\x7f\x2d\xe1\x90\xf0\xb4\x19\x9a\x5b\xb2\xeb\x86\x54\x6d\xb7\xfe\x70\x3a\x80\xaf\xf0\x79\xfa\x31\xb8\x6c\xeb\xfc\x86\x7e\x2e\x63\x4b\x3b\x36\x87\xae\x97\x6b\xb5\x91\x66\x47\x02\x2a\xad\x1b\x42\x35\x7c\x25\x66\xb3\x70\x95\x16\x30\x0b\xd3\x65\xdf\xd0\xea\x83\xe1\x04\x8f\x68\x7a\x96\xe9\xed\x2b\x98\xd3\x18\x7d\x87\x7c\xe5\xf0\x5e\xfc\x9c\x49\x16\xb3\xf2\x92\xe8\xb5\x0b\xa3\x95\x33\xef\xfa\xef\xbc\x7f\x01\x00\x00\xff\xff\x78\xa0\x3d\xa6\x5c\x04\x00\x00")

func init_dbSqlBytes() ([]byte, error) {
	return bindataRead(
		_init_dbSql,
		"init_db.sql",
	)
}

func init_dbSql() (*asset, error) {
	bytes, err := init_dbSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "init_db.sql", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0xb8, 0xca, 0x29, 0x79, 0x39, 0x68, 0xd3, 0x47, 0x95, 0x36, 0x3, 0x5, 0xac, 0x5c, 0xc9, 0xf4, 0xe3, 0x35, 0x34, 0x9c, 0x4c, 0x0, 0x7f, 0x8e, 0x22, 0xc7, 0xb7, 0x53, 0x40, 0x3d, 0x9b, 0x9f}}
	return a, nil
}

var _upsert_bandSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\xf2\xf4\x0b\x76\x0d\x0a\x51\xf0\xf4\x0b\xf1\x57\x48\x4a\xcc\x4b\x29\x56\xd0\xc8\x4c\xd1\x51\x48\x49\x2c\x49\xd4\x54\x08\x73\xf4\x09\x75\x0d\x56\xd0\x50\x31\xd4\x51\x50\x31\xd2\xe4\xf2\xf7\x53\x70\xf6\xf7\x73\xf3\xf1\x74\x0e\x01\x29\xd3\x54\x70\xf1\xe7\x52\x50\x08\x0d\x70\x71\x0c\x71\x55\x08\x76\x0d\x01\x6b\x53\xb0\x55\x50\x31\xe2\x02\x04\x00\x00\xff\xff\x7c\xf2\x04\xd0\x58\x00\x00\x00")

func upsert_bandSqlBytes() ([]byte, error) {
	return bindataRead(
		_upsert_bandSql,
		"upsert_band.sql",
	)
}

func upsert_bandSql() (*asset, error) {
	bytes, err := upsert_bandSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "upsert_band.sql", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0x73, 0x18, 0x63, 0xe3, 0x95, 0x2, 0x52, 0x53, 0xb4, 0xa9, 0x8, 0xf5, 0x13, 0xc7, 0xfc, 0x9, 0xb0, 0xe0, 0x12, 0xb1, 0x99, 0x46, 0x3f, 0x8d, 0xcd, 0xfa, 0x19, 0x80, 0xc2, 0xd4, 0x0, 0xe}}
	return a, nil
}

var _upsert_faceSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x64\xce\xbd\x0a\xc2\x30\x14\xc5\xf1\xbd\x4f\x71\x86\x0c\x2d\x64\xf1\x73\x97\x5a\x35\x50\x6e\xc0\x46\x57\x29\xc9\x6d\x09\xb4\x8d\xa4\xf5\xfd\x5d\xac\x16\x3c\xd3\x6f\x39\xf0\x57\x54\x15\x57\x03\x45\x46\xa3\xa9\x2d\x8f\x48\x23\xdb\xa9\x1e\xda\x8e\x25\x1c\x8f\x36\xfa\xe7\x14\xa2\x84\xef\xeb\x96\x1f\xde\x49\x78\x17\xba\x1f\x6c\x18\x1a\x1f\x7b\x76\x12\x63\x78\x45\xcb\x59\x72\x3f\x94\xb7\xa2\xc2\x62\xa9\x58\xc9\xd9\x62\xfd\x25\xc4\x66\xb6\xd8\x7e\x24\x76\x72\xf9\x84\xd8\x67\x89\x26\xe4\x9a\x4e\xa5\xca\x0d\xd2\xbf\x90\x0c\x47\x0d\xd2\xe6\xa2\xe8\x9c\xbc\x03\x00\x00\xff\xff\x86\xe6\x05\x1b\xd1\x00\x00\x00")

func upsert_faceSqlBytes() ([]byte, error) {
	return bindataRead(
		_upsert_faceSql,
		"upsert_face.sql",
	)
}

func upsert_faceSql() (*asset, error) {
	bytes, err := upsert_faceSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "upsert_face.sql", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0xdf, 0x87, 0x4b, 0x2e, 0xef, 0x1e, 0x52, 0xf1, 0x1c, 0x49, 0xef, 0xfd, 0x15, 0x37, 0x66, 0x6, 0xbd, 0x86, 0x4d, 0x53, 0x2f, 0x48, 0x6d, 0x95, 0x44, 0xc1, 0xbb, 0xfc, 0xe2, 0xb0, 0x1, 0x18}}
	return a, nil
}

var _upsert_idolSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\xf2\xf4\x0b\x76\x0d\x0a\x51\xf0\xf4\x0b\xf1\x57\xc8\x4c\xc9\xcf\x29\x56\xd0\xc8\x4c\xd1\x51\x48\x4a\xcc\x4b\x89\x07\x31\x52\x12\x4b\x12\x35\x15\xc2\x1c\x7d\x42\x5d\x83\x15\x34\x54\x0c\x75\x14\x54\x8c\x74\x14\x54\x8c\x35\xb9\xfc\xfd\x14\x9c\xfd\xfd\xdc\x7c\x3c\x9d\x43\x40\x7a\x34\x15\x5c\xfc\xb9\x14\x14\x42\x03\x5c\x1c\x43\x5c\x15\x82\x5d\x43\x60\x66\x28\xd8\x82\xb5\x80\x0c\x02\x31\x8d\xb9\x00\x01\x00\x00\xff\xff\xf9\xf9\xc7\x4a\x73\x00\x00\x00")

func upsert_idolSqlBytes() ([]byte, error) {
	return bindataRead(
		_upsert_idolSql,
		"upsert_idol.sql",
	)
}

func upsert_idolSql() (*asset, error) {
	bytes, err := upsert_idolSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "upsert_idol.sql", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0xf2, 0xcf, 0x2a, 0xde, 0x16, 0xb6, 0x2b, 0x87, 0xe2, 0x4b, 0x8, 0x74, 0xc3, 0x66, 0xa9, 0x82, 0x72, 0x3b, 0xdb, 0xf5, 0x96, 0x6c, 0xab, 0x8e, 0x53, 0x72, 0xe4, 0xc3, 0x73, 0xa4, 0xa, 0xb}}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// AssetString returns the asset contents as a string (instead of a []byte).
func AssetString(name string) (string, error) {
	data, err := Asset(name)
	return string(data), err
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// MustAssetString is like AssetString but panics when Asset would return an
// error. It simplifies safe initialization of global variables.
func MustAssetString(name string) string {
	return string(MustAsset(name))
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetDigest returns the digest of the file with the given name. It returns an
// error if the asset could not be found or the digest could not be loaded.
func AssetDigest(name string) ([sha256.Size]byte, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return [sha256.Size]byte{}, fmt.Errorf("AssetDigest %s can't read by error: %v", name, err)
		}
		return a.digest, nil
	}
	return [sha256.Size]byte{}, fmt.Errorf("AssetDigest %s not found", name)
}

// Digests returns a map of all known files and their checksums.
func Digests() (map[string][sha256.Size]byte, error) {
	mp := make(map[string][sha256.Size]byte, len(_bindata))
	for name := range _bindata {
		a, err := _bindata[name]()
		if err != nil {
			return nil, err
		}
		mp[name] = a.digest
	}
	return mp, nil
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"get_bands.sql": get_bandsSql,

	"get_face.sql": get_faceSql,

	"get_idol_previews.sql": get_idol_previewsSql,

	"get_idols.sql": get_idolsSql,

	"get_train_data.sql": get_train_dataSql,

	"init_db.sql": init_dbSql,

	"upsert_band.sql": upsert_bandSql,

	"upsert_face.sql": upsert_faceSql,

	"upsert_idol.sql": upsert_idolSql,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"},
// AssetDir("data/img") would return []string{"a.png", "b.png"},
// AssetDir("foo.txt") and AssetDir("notexist") would return an error, and
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		canonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(canonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{nil, map[string]*bintree{
	"get_bands.sql":         &bintree{get_bandsSql, map[string]*bintree{}},
	"get_face.sql":          &bintree{get_faceSql, map[string]*bintree{}},
	"get_idol_previews.sql": &bintree{get_idol_previewsSql, map[string]*bintree{}},
	"get_idols.sql":         &bintree{get_idolsSql, map[string]*bintree{}},
	"get_train_data.sql":    &bintree{get_train_dataSql, map[string]*bintree{}},
	"init_db.sql":           &bintree{init_dbSql, map[string]*bintree{}},
	"upsert_band.sql":       &bintree{upsert_bandSql, map[string]*bintree{}},
	"upsert_face.sql":       &bintree{upsert_faceSql, map[string]*bintree{}},
	"upsert_idol.sql":       &bintree{upsert_idolSql, map[string]*bintree{}},
}}

// RestoreAsset restores an asset under the given directory.
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	return os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
}

// RestoreAssets restores an asset under the given directory recursively.
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(canonicalName, "/")...)...)
}
